export const landingMarkup=`
<section class="landing-copy" aria-labelledby="landing-title">
 <div class="landing-kicker"><span></span> TACTICAL CO-OP / SINGAPORE</div>
 <h1 id="landing-title">CAMP:<br><em>INFECTED</em></h1>
 <p class="landing-tagline">Your next book-out isn’t guaranteed.</p>
 <p class="landing-description">Your camp is under lockdown. Find survivors, recover supplies, and find another way into camp.</p>
 <div class="landing-buttons"><button class="start-button" id="explore-camp">Play the tutorial <span aria-hidden="true">→</span></button><button class="join-button" id="meet-squad">Meet the squad <span aria-hidden="true">→</span></button></div>
 <div class="landing-meta"><span>1–3 PLAYERS</span><i></i><span>CO-OP PLANNED</span><i></i><span>ISOMETRIC SURVIVAL</span></div>
 <small class="landing-preview-note">Free development build · Desktop keyboard & mouse</small>
</section>
<div class="landing-scene-label" aria-hidden="true"><span class="scene-coordinate">SECTOR 01 / 01° N</span><strong>THE GUARDHOUSE</strong><span class="scene-status"><i></i> LOCKDOWN IN EFFECT</span><div class="scene-label-rule"></div><small>PASS OFFICE → GUARD REST → CONTROLLED AREA</small></div>
<section class="landing-features" aria-label="Game direction">
 <div><span class="feature-number">01 /</span><strong>THREE SOLDIERS. ONE WAY OUT.</strong><p>Built around a squad of up to three.</p></div>
 <div><span class="feature-number">02 /</span><strong>FAMILIAR GROUND. NEW THREAT.</strong><p>Singapore-inspired kit and camp interiors.</p></div>
 <div><span class="feature-number">03 /</span><strong>FIGHT. RETREAT. REGROUP.</strong><p>Cover, escape routes, and a way back into the fight.</p></div>
</section>
<div class="landing-more">
<section id="the-game" class="story-section"><div><span class="eyebrow">WELCOME BACK TO CAMP</span><h2>Same routine.<br>Different nightmare.</h2></div><div><p>The gate is sealed. The radio is silent. Something is moving inside the guardhouse.</p><p>CAMP: INFECTED is a stylised survival game set in a fictional Singapore military camp. Search familiar spaces, rescue the people left behind, and uncover what the lockdown is hiding.</p><a href="/game.html">Enter the Main Gate tutorial →</a></div></section>
<section class="pillars" aria-label="Gameplay pillars"><article><span>01 / SURVIVE</span><h3>Make space.<br>Stay alive.</h3><p>Use substantial cover. Break line of sight. Reload somewhere safe. Survival should reward decisions, not just a bigger health bar.</p></article><article><span>02 / EXPLORE</span><h3>Every place<br>has a story.</h3><p>From the pass office to the cookhouse, familiar camp routines become clues to an unfamiliar outbreak.</p></article><article><span>03 / REGROUP</span><h3>Leave no one<br>behind.</h3><p>A complete solo experience is the first milestone. Online squads of two and three are planned for later development.</p></article></section>
<section id="field-notes" class="status-section"><span class="eyebrow">FIELD NOTES / BUILD 0.2</span><h2>A camp worth surviving.</h2><p>Start with a small playable operation. Help shape what comes next.</p><div class="status-grid"><div><b>PLAYABLE NOW</b><p>Main Gate tutorial · movement · supplies · SAR 21 combat · recovery · extraction</p></div><div><b>IN DEVELOPMENT</b><p>Online co-op · connected camp sectors · named encounters · campaign progression</p></div></div><details><summary>What is included in this build?</summary><p>An early solo tutorial and the existing character art inspection. It is a development slice, not the full campaign. Keyboard and mouse are required for gameplay.</p></details><details><summary>Can I play with friends?</summary><p>Online multiplayer is planned. This build runs solo locally; it does not create online rooms.</p></details><details><summary>Is this an official SAF game?</summary><p>No. This is an independent game in a fictional camp, inspired by publicly available Singapore military references.</p></details></section>
<footer><strong>CAMP: INFECTED</strong><span>Independent game · In development</span><a href="https://github.com/Yanliangchan/Camp_Infected" target="_blank" rel="noopener">Follow development →</a><a href="/review.html">Character & environment inspection →</a><small>Fictional setting. No affiliation with MINDEF or the SAF.</small></footer></div>
<dialog id="deployment-dialog"><form method="dialog"><button class="dialog-close" aria-label="Close deployment lobby">×</button></form><span class="eyebrow">DEPLOYMENT / SECTOR 01</span><h2>Main Gate</h2><p>Find another way into camp. Recover supplies, clear the access route, and reach the pedestrian gate.</p><div class="squad-slot"><b>01</b><span>YOU / SOLO OPERATOR<small>SAR 21 · Field dressing · Standard issue</small></span><i>READY</i></div><p class="lobby-note">Solo tutorial · Keyboard & mouse<br>Online squad deployment is in development.</p><a class="deploy-link" href="/game.html">Deploy to Main Gate →</a></dialog>
<button class="motion-toggle" id="landing-motion" aria-pressed="false">Pause motion <span aria-hidden="true">Ⅱ</span></button>`;
