import * as THREE from 'three';
import {buildPreviewRoom} from './previewRoom';
import {buildDungeonRoom} from './dungeonRoom';
import {createCharacter,animateCharacter,setCharacterWeapon,type CharacterMotion} from './characters';
import {CharacterPreviewInput} from './characterPreviewInput';
import '@fontsource/dm-sans/400.css';
import '@fontsource/dm-sans/500.css';
import '@fontsource/dm-sans/600.css';
import '@fontsource/dm-sans/700.css';
import '@fontsource/barlow-condensed/600.css';
import '@fontsource/barlow-condensed/700.css';
import './review.css';
import './landing.css';
import {landingMarkup} from './landingUI';
import {buildLandingAtmosphere} from './landingAtmosphere';

document.body.innerHTML=`<main id="review-app" data-view="landing">
<header class="review-header"><div class="review-brand"><span class="brand-icon">CI</span><strong>CAMP<span>: INFECTED</span></strong></div><span class="review-badge"><i></i> VISUAL REVIEW 03</span></header>
<section id="art-stage" aria-label="Interactive 3D art preview"></section>
${landingMarkup}
<section class="inspection-copy" hidden><span class="inspection-kicker" id="inspect-kicker">PERSONNEL / 01</span><h2 id="inspect-title">The soldier</h2><p id="inspect-description"></p><div class="inspection-details" id="inspect-details"></div></section>
<div class="stage-caption"><span id="stage-kicker">SECTOR 01</span><strong id="stage-title">The checkpoint</strong><small id="stage-detail">Guardhouse · Main gate · Singapore-inspired kit</small></div>
<div class="model-controls" hidden><button id="rotate-left" title="Rotate left">↶</button><span>ROTATE</span><button id="rotate-right" title="Rotate right">↷</button><button id="helmet-detail" aria-pressed="false">Helmet detail</button><button id="kit-detail" aria-pressed="false">Vest &amp; belt</button><button id="armband-detail" hidden aria-pressed="false">Armband detail</button><div class="pose-buttons"><button data-motion="idle" aria-pressed="true">Idle</button><button data-motion="walk">Walk</button><button data-motion="sprint">Sprint</button><button data-motion="crawl">Crawl</button></div><small>WASD · double-tap W to sprint · Shift + WASD to crawl</small></div>
<div class="room-controls" hidden><button data-room-camera="overview" aria-pressed="true">Room overview</button><button data-room-camera="game">Game camera · 1.5×</button><button data-room-camera="game2">Game camera · 2×</button><button data-room-camera="counter">Pass counter</button><button data-room-camera="screening">Screening</button><button data-room-camera="rest">Guard rest</button><button data-room-camera="bunks">Bunks</button><button data-room-camera="toilets">Toilets</button><button data-room-camera="bed">Bed detail</button><button data-room-camera="door">Doorway</button><button id="room-routes" aria-pressed="false">Show routes</button><button id="room-lighting" aria-pressed="false">Inspection light</button></div><nav class="review-tabs" aria-label="Review views"><button data-view="landing" class="active"><span>01</span> Landing</button><button data-view="soldier"><span>02</span> Soldier</button><button data-view="infected"><span>03</span> Infected</button><button data-view="gatekeeper"><span>04</span> Security Trooper</button><button data-view="room"><span>05</span> First room</button></nav>
<div class="review-note">Development build · Character and environment inspection</div>
<div id="graphics-error" hidden></div></main>`;
document.body.appendChild(document.querySelector('.landing-more')!);
const stage=document.getElementById('art-stage')!,app=document.getElementById('review-app')!;
const scene=new THREE.Scene();scene.background=new THREE.Color('#dbe2dd');
const camera=new THREE.OrthographicCamera(-1,1,1,-1,.1,160);
let renderer:THREE.WebGLRenderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});}catch{const error=document.getElementById('graphics-error')!;error.hidden=false;error.textContent='Enable hardware acceleration to view the 3D art preview.';throw new Error('WebGL unavailable');}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.NeutralToneMapping;
renderer.toneMappingExposure=1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;stage.appendChild(renderer.domElement);
const hemi=new THREE.HemisphereLight(0xfff3df,0xa5ad9b,1.4);scene.add(hemi);
const sun=new THREE.DirectionalLight(0xffe3c2,2.2);sun.position.set(-18,30,18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-25;sun.shadow.camera.right=25;sun.shadow.camera.top=25;sun.shadow.camera.bottom=-25;sun.shadow.camera.far=90;sun.shadow.normalBias=.018;sun.shadow.bias=-.0003;sun.shadow.radius=4;scene.add(sun,sun.target);
const fill=new THREE.DirectionalLight(0xc8e0f6,.55);fill.position.set(20,14,25);scene.add(fill);
const room=buildPreviewRoom(scene);const dungeon=buildDungeonRoom(scene);dungeon.visible=false;const dungeonActors=new THREE.Group();dungeon.add(dungeonActors);for(const [kind,role,x,z,yaw]of [['player','soldier',0,6,.65],['player','soldier',3,5.7,.5],['player','soldier',6,6,.3],['boss','Security Trooper',9.3,-2.4,-.7],['infected','cadet',4.7,.2,.5]] as [string,string,number,number,number][]){const actor=createCharacter(kind,role);actor.position.set(x,.05,z);actor.rotation.y=yaw;dungeonActors.add(actor);}
const landingAtmosphere=buildLandingAtmosphere(scene);const reducedMotionQuery=matchMedia("(prefers-reduced-motion: reduce)");let motionPaused=reducedMotionQuery.matches;const lineups=new THREE.Group();scene.add(lineups);
const soldier=createCharacter('player','soldier');setCharacterWeapon(soldier,'SAR 21');
const infected=createCharacter('infected','cadet');
const gatekeeper=createCharacter('boss','Security Trooper');
const characterModels={soldier,infected,gatekeeper};
for(const g of Object.values(characterModels)){lineups.add(g);g.visible=false;}
const extras=new THREE.Group();room.add(extras);
for(const [kind,role,x,z,yaw]of [['player','soldier',-2,5,.65],['npc','cookhouse',-7,4,.3],['infected','cadet',6,5,-.7]] as [string,string,number,number,number][]){const actor=createCharacter(kind,role);actor.position.set(x,.05,z);actor.rotation.y=yaw;extras.add(actor);}
const pedestal=new THREE.Mesh(new THREE.CylinderGeometry(.75,.78,.045,64),new THREE.MeshStandardMaterial({color:0xcbd7ce,roughness:.78}));pedestal.position.y=-.035;lineups.add(pedestal);
const pedestalRing=new THREE.Mesh(new THREE.TorusGeometry(.68,.004,4,64),new THREE.MeshBasicMaterial({color:0x93a99a}));pedestalRing.rotation.x=Math.PI/2;pedestalRing.position.y=-.01;lineups.add(pedestalRing);
type View='landing'|'soldier'|'infected'|'gatekeeper'|'room';let view:View='landing',motion:CharacterMotion='idle',helmetDetail=false,armbandDetail=false,kitDetail=false,rotation=.0,lastTime=performance.now(),elapsed=0;
const texts:Record<string,{kicker:string,title:string,description:string,details:string[]}>={
 soldier:{kicker:'PERSONNEL / 01',title:'The soldier',description:'Refined against your SAF photos: fitted helmet and straps, digital fabric, layered webbing and a supported SAR 21.',details:['Smaller facial features & clear helmet silhouette','Reference fabric, collar, pockets & webbing','Bare hands, fitted rifle & articulated knees']},
 infected:{kicker:'INFECTED / 01',title:'The recruit',description:'Familiar camp kit, an unsteady posture, and a readable face. The infection changes the character without burying it in gore.',details:['Same character family as the soldier','Altered expression & uneven stance','A silhouette readable from the game camera']},
 gatekeeper:{kicker:'NAMED ENCOUNTER / 01',title:'Security Trooper',description:'A checkpoint guard with a distinct presence. This is an art study for the first encounter, with gameplay kept separate.',details:['Helmet, goggles & field webbing','Black armband with orange lettering','First boss visual study']},
 room:{kicker:'SECTOR / 01',title:'Pass office',description:'A 40 × 16 metre guardhouse complex: visitor screening, an open combat floor, clear doorways and an orderly guard rest wing.',details:['Off-white plaster, grey tile & olive steel','Glazed counter, pass trays & office furniture','Inspect at the close-up game camera']}
};
let roomCamera='overview',inspectionLight=false;let cameraMotion:CharacterMotion='idle',cameraRotation=0;
function resize(){app.dataset.roomCamera=roomCamera;const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h);const aspect=w/h;const model=view!=='landing'&&view!=='room';let vh=model?(kitDetail?.83:armbandDetail?.78:helmetDetail?.96:motion==='crawl'?2.45:view==='gatekeeper'?2.3:2.05):Math.max(24,34/aspect);if(view==='landing')vh=Math.max(17,22/aspect);if(view==='room')vh=({counter:5.6,game:8/1.5,game2:4,screening:5.6,rest:11,bunks:11,toilets:7,bed:4.8,door:6} as Record<string,number>)[roomCamera]??Math.max(28.5,43/aspect);camera.left=-vh*aspect/2;camera.right=vh*aspect/2;camera.top=vh/2;camera.bottom=-vh/2;camera.updateProjectionMatrix();const target=model?new THREE.Vector3(motion==='crawl'?Math.sin(rotation)*.28:0,helmetDetail?(view==='gatekeeper'?1.17:view==='infected'?1.01:1.07):motion==='crawl'?.28:view==='gatekeeper'?.75:.6,motion==='crawl'?Math.cos(rotation)*.28:0):new THREE.Vector3(-1,0,1);if(view==='landing')target.set(3.5,.8,2.5);if(view==='room'){const centers:Record<string,[number,number]>={overview:[13,3],game:[3,6.25],game2:[3,6.25],counter:[-3.2,-1.5],screening:[1,8.4],rest:[18,2.5],bunks:[28,5.5],toilets:[28,-2.3],bed:[29.6,9.25],door:[13,0]};const c=centers[roomCamera]??centers.overview;target.set(c[0],.8,c[1]);}if(kitDetail)target.set(0,.47,.08);if(armbandDetail&&view==='gatekeeper')target.set(-.26,.66,.035).applyAxisAngle(new THREE.Vector3(0,1,0),rotation);const elevation=THREE.MathUtils.degToRad(model?23:38),azimuth=THREE.MathUtils.degToRad(model?15:view==='room'&&roomCamera==='bed'?-155:view==='room'&&['bunks','toilets','door'].includes(roomCamera)?-25:45);const dir=new THREE.Vector3(Math.sin(azimuth)*Math.cos(elevation),Math.sin(elevation),Math.cos(azimuth)*Math.cos(elevation));camera.position.copy(target).addScaledVector(dir,50);camera.lookAt(target);fill.intensity=view==='room'?(inspectionLight?.65:.18):model?1.4:.55;hemi.intensity=view==='room'?(inspectionLight?1.2:.46):1.4;sun.intensity=view==='room'?(inspectionLight?1.5:.8):2.2;hemi.color.setHex(view==='room'?0xdde4db:0xfff3df);hemi.groundColor.setHex(view==='room'?0x304637:0xa5ad9b);scene.background=view==='landing'?null:new THREE.Color(view==='room'?'#192823':'#dbe2dd');renderer.setClearColor(0x0d1715,view==='landing'?0:1);if(view==='landing'){hemi.intensity=.65;hemi.color.setHex(0xc5d6ce);hemi.groundColor.setHex(0x24372c);sun.intensity=1.1;fill.intensity=.35;}sun.shadow.camera.left=view==='room'?-35:-25;sun.shadow.camera.right=view==='room'?35:25;sun.shadow.camera.top=view==='room'?35:25;sun.shadow.camera.bottom=view==='room'?-35:-25;sun.shadow.camera.updateProjectionMatrix();}
function setView(next:View){kitDetail=false;document.getElementById("kit-detail")!.setAttribute("aria-pressed","false");armbandDetail=false;document.getElementById('armband-detail')!.hidden=next!=='gatekeeper';document.getElementById('armband-detail')!.setAttribute('aria-pressed','false');view=next;app.dataset.view=next;document.querySelector('.review-badge')!.innerHTML=next==='landing'?'<i></i> IN DEVELOPMENT':'<i></i> VISUAL REVIEW 03';const model=!['landing','room'].includes(next);room.visible=false;dungeon.visible=next==='room'||next==='landing';landingAtmosphere.group.visible=next==='landing';lineups.visible=model;document.querySelector<HTMLElement>('.room-controls')!.hidden=next!=='room';for(const [key,g]of Object.entries(characterModels))g.visible=key===next;
document.querySelector<HTMLElement>('.landing-copy')!.hidden=next!=='landing';document.querySelector<HTMLElement>('.inspection-copy')!.hidden=next==='landing';document.querySelector<HTMLElement>('.model-controls')!.hidden=!model;
document.querySelector<HTMLElement>('.stage-caption')!.hidden=model;
for(const button of document.querySelectorAll<HTMLButtonElement>('.review-tabs button')){button.classList.toggle('active',button.dataset.view===next);button.setAttribute('aria-pressed',String(button.dataset.view===next));}
const text=texts[next];if(text){document.getElementById('inspect-kicker')!.textContent=text.kicker;document.getElementById('inspect-title')!.textContent=text.title;document.getElementById('inspect-description')!.textContent=text.description;const details=document.getElementById('inspect-details')!;details.replaceChildren();for(const detail of text.details){const p=document.createElement('span');p.textContent=detail;details.appendChild(p);}}
document.getElementById('stage-title')!.textContent=next==='room'?'Pass office / Lockdown':'The checkpoint';resize();}
for(const button of document.querySelectorAll<HTMLButtonElement>('.review-tabs button'))button.onclick=()=>setView(button.dataset.view as View);
document.getElementById('rotate-left')!.onclick=()=>{rotation-=Math.PI/4;};document.getElementById('rotate-right')!.onclick=()=>{rotation+=Math.PI/4;};document.getElementById('helmet-detail')!.onclick=()=>{kitDetail=false;document.getElementById('kit-detail')!.setAttribute('aria-pressed','false');armbandDetail=false;document.getElementById('armband-detail')!.setAttribute('aria-pressed','false');helmetDetail=!helmetDetail;motion='idle';document.getElementById('helmet-detail')!.setAttribute('aria-pressed',String(helmetDetail));resize();};
document.getElementById('armband-detail')!.onclick=()=>{kitDetail=false;document.getElementById('kit-detail')!.setAttribute('aria-pressed','false');armbandDetail=!armbandDetail;helmetDetail=false;motion='idle';document.getElementById('helmet-detail')!.setAttribute('aria-pressed','false');document.getElementById('armband-detail')!.setAttribute('aria-pressed',String(armbandDetail));resize();};
document.getElementById('kit-detail')!.onclick=()=>{kitDetail=!kitDetail;armbandDetail=false;helmetDetail=false;motion='idle';document.getElementById('kit-detail')!.setAttribute('aria-pressed',String(kitDetail));document.getElementById('helmet-detail')!.setAttribute('aria-pressed','false');document.getElementById('armband-detail')!.setAttribute('aria-pressed','false');resize();};const previewInput=new CharacterPreviewInput();
for(const button of document.querySelectorAll<HTMLButtonElement>('[data-motion]'))button.onclick=()=>{previewInput.reset();kitDetail=false;document.getElementById('kit-detail')!.setAttribute('aria-pressed','false');armbandDetail=false;document.getElementById('armband-detail')!.setAttribute('aria-pressed','false');helmetDetail=false;document.getElementById('helmet-detail')!.setAttribute('aria-pressed','false');motion=button.dataset.motion as CharacterMotion;resize();};
const movementKeys=['KeyW','KeyA','KeyS','KeyD','ShiftLeft','ShiftRight'];
addEventListener('keydown',event=>{if(!movementKeys.includes(event.code)||['landing','room'].includes(view))return;event.preventDefault();previewInput.setKey(event.code,true,performance.now());motion=previewInput.motion;});
addEventListener('keyup',event=>{if(!movementKeys.includes(event.code))return;previewInput.setKey(event.code,false,performance.now());motion=previewInput.motion;});
addEventListener('blur',()=>{previewInput.reset();motion='idle';});
for(const button of document.querySelectorAll<HTMLButtonElement>('[data-room-camera]'))button.onclick=()=>{roomCamera=button.dataset.roomCamera!;for(const other of document.querySelectorAll<HTMLButtonElement>('[data-room-camera]'))other.setAttribute('aria-pressed',String(other===button));resize();};
document.getElementById('room-routes')!.onclick=()=>{const routes=dungeon.userData.routePreview as THREE.Group;routes.visible=!routes.visible;document.getElementById('room-routes')!.setAttribute('aria-pressed',String(routes.visible));};document.getElementById('room-lighting')!.onclick=()=>{inspectionLight=!inspectionLight;document.getElementById('room-lighting')!.setAttribute('aria-pressed',String(inspectionLight));resize();};
const resizeObserver=new ResizeObserver(resize);resizeObserver.observe(stage);addEventListener('resize',resize);resize();
function frame(now:number){requestAnimationFrame(frame);if(cameraMotion!==motion||cameraRotation!==rotation){cameraMotion=motion;cameraRotation=rotation;resize();}const dt=Math.min((now-lastTime)/1000,.05);lastTime=now;elapsed+=dt;
pedestal.scale.z=motion==='crawl'?1.55:1;pedestal.rotation.y=motion==='crawl'?rotation:0;pedestalRing.scale.y=motion==='crawl'?1.55:1;pedestalRing.rotation.z=motion==='crawl'?rotation:0;for(const g of Object.values(characterModels)){g.rotation.y=rotation;const armed=g.userData.armed;if(kitDetail)g.userData.armed=false;animateCharacter(g,motion!=='idle',elapsed,motion);g.userData.armed=armed;}
for(const g of dungeonActors.children)animateCharacter(g as THREE.Group,false,view==='landing'&&motionPaused?0:elapsed);for(const g of extras.children)animateCharacter(g as THREE.Group,false,elapsed);
for(const button of document.querySelectorAll<HTMLButtonElement>('[data-motion]'))button.setAttribute('aria-pressed',String(button.dataset.motion===motion));for(const g of Object.values(characterModels)){const w=g.userData.weapon as THREE.Group|undefined;if(w)w.visible=!kitDetail;}app.dataset.detail=kitDetail?'kit':helmetDetail?'helmet':armbandDetail?'armband':'body';app.dataset.motion=motion;landingAtmosphere.update(elapsed,motionPaused);if(view==='landing'){const drift=motionPaused?0:Math.sin(elapsed*.13)*.12;camera.position.x+=drift;camera.lookAt(3.5,.8,2.5);renderer.render(scene,camera);camera.position.x-=drift;}else renderer.render(scene,camera);app.dataset.drawCalls=String(renderer.info.render.calls);app.dataset.triangles=String(renderer.info.render.triangles);
}
document.getElementById('explore-camp')!.onclick=()=>{document.querySelector<HTMLDialogElement>('#deployment-dialog')!.showModal();};document.getElementById('meet-squad')!.onclick=()=>setView('soldier');const motionToggle=document.getElementById('landing-motion')!;function syncMotion(){motionToggle.setAttribute('aria-pressed',String(motionPaused));motionToggle.textContent=motionPaused?'Resume motion ▷':'Pause motion Ⅱ';app.dataset.motionPaused=String(motionPaused);}motionToggle.onclick=()=>{motionPaused=!motionPaused;syncMotion();};reducedMotionQuery.addEventListener('change',e=>{motionPaused=e.matches;syncMotion();});syncMotion();setView(location.pathname.endsWith('/review.html')?'soldier':'landing');requestAnimationFrame(frame);
